In [1]:
import duckdb as db

In [2]:
con = db.connect(database='dados_duckdb.db', read_only=False)

In [3]:
df = con.execute('SELECT * FROM produtos').fetch_df()
df.head(10)

      id nm_produto id_categoria  id_fornecedor  vl_preco
0  10001   PARAFUSO         BT10            100     100.0
1  10002    MARTELO         BT50            100    1500.0
2  10004      SERRA         BT50            100     200.0
3  10005    MACHADO         BT50            100     100.0
4  10003      PREGO         BT10            100      60.0

In [4]:
df2 = df.drop(columns=['id_categoria', 'id_fornecedor'])
df2.head(10)

      id nm_produto  vl_preco
0  10001   PARAFUSO     100.0
1  10002    MARTELO    1500.0
2  10004      SERRA     200.0
3  10005    MACHADO     100.0
4  10003      PREGO      60.0

In [5]:
con.execute('''
CREATE TABLE IF NOT EXISTS dim_produtos (
    id_produto BIGINT PRIMARY KEY,
    nm_produto TEXT,
    vl_preco FLOAT
)
''')

In [6]:
df_dim = con.execute('SELECT * FROM dim_produtos').fetch_df()
df_dim.head(10)

Empty DataFrame
Columns: [id_produto, nm_produto, vl_preco]
Index: []

In [7]:
con.execute('insert into dim_produtos SELECT * FROM df2')

In [8]:
df_dim = con.execute('SELECT * FROM dim_produtos').fetch_df()
df_dim.head(10)

   id_produto nm_produto  vl_preco
0       10001   PARAFUSO     100.0
1       10002    MARTELO    1500.0
2       10004      SERRA     200.0
3       10005    MACHADO     100.0
4       10003      PREGO      60.0

In [9]:
con.close()